### ISSUE TITLE
modify dies with stack trace

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#23]
```
Traceback (most recent call last):
  File "intelmq/lib/bot.py", line 97, in start
    self.process()
  File "/home/aaron/intelmq/intelmq/bots/experts/modify/expert.py", line 70, in process
    apply_action(event, default_action)
  File "/home/aaron/intelmq/intelmq/bots/experts/modify/expert.py", line 35, in apply_action
    event.add(name, value.format(msg=event), sanitize=True, force=True)
KeyError: u'malware.name'
2015-11-17 18:27:50,069 - modify-expert - INFO - Last Correct Message(event): {u'source.ip': u'27.27.241.236', u'feed.accuracy': 0.0, u'feed.url': u'https://lists.blocklist.de/lists/mail.txt', u'protocol.application': u'smtp', u'event_description.text': u'IP reported as having run attacks on the service Mail, Postfix', u'time.observation': u'2015-11-17T17:03:32+00:00', u'raw': u'MjcuMjcuMjQxLjIzNg==', u'classification.identifier': u'smtp', u'classification.type': u'ids alert', u'classification.taxonomy': u'Intrusion Attempts', u'feed.name': u'
2015-11-17 18:27:50,069 - modify-expert - INFO - Current Message(event): {u'source.ip': u'223.4.233.212', u'time.source': u'2015-11-11T06:47:04+00:00', u'feed.accuracy': 0.0, u'feed.url': u'https://dragonresearchgroup.org/insight/sshpwauth.txt', u'protocol.application': u'ssh', u'time.observation': u'2015-11-17T17:03:36+00:00', u'raw': u'TkEgICAgICAgICAgIHwgIE5BICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgfCAgICAyMjMuNC4yMzMuMjEyICB8ICAyMDE1LTExLTExIDA2OjQ3OjA0ICB8ICBzc2hwd2F1dGg=', u'classification.type': u'brute-force', u'destination.port': 22, u
2015-11-17 18:27:50,069 - modify-expert - INFO - Bot will restart in 15 seconds.
```

**Comment by sebix** [comment]
I'm not sure what the issue is here from your perspective:

1) A configuration error. But without configuration and examples, expected outcome etc. I can't give advices.
2) The bot should not fail in these cases. But what should happen instead? The current behavior is what we have everywhere: Message is dumped along with traceback. Sysadmin can examine and fix the issue. Reinject it.

**Comment by sebix** [comment]
Also, modify is not cert.at specific, it's in https://github.com/certtools/intelmq.

**Comment by aaronkaplan** [comment]
Yes, sure. See also #402
I simply documented it here so that we can't forget.

**Comment by sebix** [comment]
The paragraph from #402 which applies here:

> an expert bot or output bot MUST assume that data it receives is incomplete (though it can assume that it's syntactically and semantically valid). If some key-value pairs in an event are missing, it MUST either assume sane default values and complain (log) and continue to pass on the event OR it MUST reject the event (dump it - as above) and continue with the next event. It must never stop processing.

So, what should be done here in case of modify? Which case does apply here:

> it MUST either assume sane default values and complain (log) and continue to pass on the event

What's the default?

> OR it MUST reject the event (dump it - as above) and continue with the next event

That's currently possible/implemented.

**Comment by aaronkaplan** [comment]
"That's currently possible/implemented" -> let's have that as default. Currently the whole system stops at every possibility that it can stop. That's wrong.

**Comment by aaronkaplan** [comment]
"So, what should be done here in case of modify?" -> in the particular case right now - still need to figure out the root cause error . It's not clear. There is no .dump file either

**Comment by sebix** [comment]
> "That's currently possible/implemented" -> let's have that as default. Currently the whole system stops at every possibility that it can stop. That's wrong.

It is default:
- https://github.com/certat/intelmq/blob/master/intelmq/conf/defaults.conf#L3
- https://github.com/certtools/intelmq/blob/master/intelmq/conf/defaults.conf#L3

**Comment by sebix** [comment]
Closed, it was a configuration issue.
