### ISSUE TITLE
intelmqcli: minor bug - pls fail gracefully if no contact known

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#37]
Sometimes, some events make it through all the way from the collector to the pg DB but there is no contact info nor an ASN.
Of course, not much can be done with these kinds of events.

However, when [a](sending all), you will get a stack trace for those:

```
Traceback (most recent call last):
  File "./intelmqcli", line 681, in <module>
    query_by_as(int(item['asn']), automatic=True,
TypeError: int() argument must be a string or a number, not 'NoneType'
```

Let's fail gracefully in this case. and just ignore the data and/or print a warning.

**Comment by aaronkaplan** [comment]
Addendum:

After all other events have ben sent out via [a], of course also there is no ASN for these remaining events, so there is another code line which will stack trace when calling intelmqcli (again) :

```
Traceback (most recent call last):
  File "./intelmqcli", line 663, in <module>
    asn_count = count_by_asn(feed=args.feed)
  File "./intelmqcli", line 587, in count_by_asn
    max_asn_length = max([len(row['asn']) for row in asn_count if row['asn']])
ValueError: max() arg is an empty sequence
```
