### ISSUE TITLE
postgresql output: deal with unexpected closed connections

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#39]
See also #38: 

```
 --------------------------------------------------
{u'bot_id': u'postgresql-output',
 u'message': {u'__type': u'Event',
              u'classification.identifier': u'c&c server',
              u'classification.taxonomy': u'Malicious Code',
              u'classification.type': u'c&c',
              u'destination.port': 6667,
              u'extra': u'{"feed_id": "4e4cdd50289b071f114f0fb1a06e2eb1"}',
              u'feed.name': u'n6stomp',
              u'feed.url': u'stomp://n6stream.cert.pl:61614//exchange/cert.at/#',
              u'notify': True,
              u'raw': XXX=',
              u'source.fqdn': u'XXX.example.comXXX',
              u'time.observation': u'2015-12-11T12:16:21+00:00',
              u'time.source': u'2015-12-11T01:36:03+00:00'},
 u'source_queue': u'postgresql-output-queue',
 u'traceback': [u'Traceback (most recent call last):',
                u'  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/lib/bot.py", line 97, in start',
                u'    self.process()',
                u'  File "/usr/local/lib/python2.7/dist-packages/intelmq-1.0.0-py2.7.egg/intelmq/bots/outputs/postgresql/output.py", line 57, in process',
                u'    self.cur.execute(query, values)',
                u'OperationalError: SSL connection has been closed unexpectedly',
                u'']}
```

**Comment by aaronkaplan** [comment]
fixed in github/certtools/ad5bb14e774e9fb0d22156c0856b4c7311052188
