### ISSUE TITLE
bug: intelmqcli crash

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#67]
After pressing "send [a]ll"

```
(English version below)
...
Traceback (most recent call last):
  File "./intelmqcli", line 599, in <module>
    main()
  File "./intelmqcli", line 596, in main
    IntelMQCLIContoller()
  File "./intelmqcli", line 205, in __init__
    taxonomy=args.taxonomy)
  File "./intelmqcli", line 374, in query_by_as
    quietprint('\n'.join(attachment_lines[:height - 5]))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 67: ordinal not in range(128)

```

**Comment by aaronkaplan** [comment]
Can be reproduced also in [t] table mode.
