### ISSUE TITLE
intelmqcli_create_reports stacktrace

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#83]
Calling the script like this:

Result:

``` bash
aaron@hostname-2 ~/intelmq/intelmq/bin % python3.4 ./intelmqcli_create_reports.py                                                                                                                                 master
Traceback (most recent call last):
  File "./intelmqcli_create_reports.py", line 117, in <module>
    main()
  File "./intelmqcli_create_reports.py", line 114, in main
    IntelMQCLIContoller()
  File "/home/aaron/intelmq/intelmq/lib/intelmqcli.py", line 323, in __init__
    self.init()
  File "./intelmqcli_create_reports.py", line 50, in init
    if not self.rt.login():
  File "/home/aaron/python-rt/rt.py", line 334, in login
    without_login=True)) == 200
  File "/home/aaron/python-rt/rt.py", line 239, in __request
    raise UnexpectedResponse('Received status code %d instead of 200.' % response.status_code)
rt.UnexpectedResponse: Received status code 504 instead of 200.
```

**Comment by sebix** [comment]
504 is a gateway timeout, can you connect to the api with netcat or
other such tools?

**Comment by aaronkaplan** [comment]
I can connect with the rt-collectors from the same host.

**Comment by sebix** [comment]
Works for me™
